project_id = "mwshudivoqwjdiidhalm"

[functions.sync-leaderboard]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.game-action]
verify_jwt = false

[functions.passive-income]
verify_jwt = false
